from typing import Any

class MarkerEnvironment:
    implementation_name: Any
    implementation_version: Any
    os_name: Any
    platform_machine: Any
    platform_python_implementation: Any
    platform_release: Any
    platform_system: Any
    platform_version: Any
    python_full_version: Any
    python_version: Any
    sys_platform: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def current(cls, *args, **kwargs) -> Any: ...

class Requirement:
    extras: Any
    marker: Any
    name: Any
    version_or_url: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def evaluate_extras_and_python_version(self, *args, **kwargs) -> Any: ...
    def evaluate_markers(self, *args, **kwargs) -> Any: ...
    def evaluate_markers_and_report(self, *args, **kwargs) -> Any: ...
    def __eq__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class Version:
    dev: Any
    epoch: Any
    major: Any
    micro: Any
    minor: Any
    post: Any
    pre: Any
    release: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def any_prerelease(self, *args, **kwargs) -> Any: ...
    def bump(self, *args, **kwargs) -> Any: ...
    @classmethod
    def lowest(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def parse(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def parse_star(cls, *args, **kwargs) -> Any: ...
    def __eq__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class VersionSpecifier:
    operator: Any
    version: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def contains(self, *args, **kwargs) -> Any: ...
    def __contains__(self, other) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class VersionSpecifiers:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __getitem__(self, index) -> Any: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...

def resolve(*args, **kwargs) -> Any: ...
